SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE DATABASE IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 ;
ALTER TABLE `sakila`.`city` CHANGE COLUMN `city` `city` VARCHAR (85) NOT NULL  ;
ALTER TABLE `sakila`.`payment` CHANGE COLUMN `rental_id` `rental_id` INT  NOT NULL DEFAULT NULL  , DROP FOREIGN KEY `fk_payment_rental` ;
ALTER TABLE `sakila`.`payment` ADD CONSTRAINT `fk_payment_rental` FOREIGN KEY (`rental_id` ) REFERENCES `sakila`.`rental` (`rental_id` ) ON DELETE SET NULL ON UPDATE CASCADE ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
